server:
  port: 9090
  context-path: /testservice
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/localslmldb?useSSL=false
    username: root
    password: root  jpa:    show-sql: false    hibernate:      ddl-auto: validate
      naming:        strategy: org.hibernate.cfg.ImprovedNamingStrategy    properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect 